"""Write and run the Geant4-DNA macros for the chosen story event.

1. delta:   the delta electron (energy from the patient-scale event), many
            independent histories in liquid water, G4EmDNAPhysics_option4.
2. primary: the fast recoil electron over a 40 µm segment centred on the
            hand-off point, G4EmDNAPhysics_option2 (Born models valid to 1 MeV).
            It starts 20 µm upstream with its energy at the hand-off plus the
            energy it loses over 20 µm (estimated from a first short run).
Usage: python3 sim/run_dna.py [n_delta]
"""
import json, os, subprocess, sys
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
W = os.path.join(HERE, "work")
RUNS = os.path.join(W, "runs")
MAC = os.path.join(HERE, "macros")
REC = np.dtype([("ev", "<i4"), ("track", "<i4"), ("parent", "<i4"), ("proc", "<i4"), ("x", "<f4"), ("y", "<f4"), ("z", "<f4"),
                ("edep", "<f4"), ("t", "<f4"), ("ekin", "<f4")])


def macro(name, physics, energy_keV, start_nm, half_um, n, seed, threads=4):
    text = f"""# Generated by sim/run_dna.py for the chosen story event.
/control/verbose 1
/run/verbose 1
/run/numberOfThreads {threads}
/nine/physics {physics}
/nine/out work/runs/{name}
/nine/energy {energy_keV:.4f} keV
/nine/start {start_nm[0]} {start_nm[1]} {start_nm[2]} nm
/nine/dir 0 0 1
/nine/half {half_um[0]} {half_um[1]} {half_um[2]} um
/nine/init
/run/initialize
/random/setSeeds {seed} {seed + 17}
/run/beamOn {n}
"""
    p = os.path.join(MAC, name + ".mac")
    open(p, "w").write(text)
    return p


def run(mac, log):
    for f in os.listdir(RUNS):
        if f.startswith(os.path.basename(mac)[:-4] + "_t") and f.endswith(".bin"):
            os.remove(os.path.join(RUNS, f))
    env = dict(os.environ)
    cmd = f". {HERE}/env.sh && {HERE}/build/nine_dna {mac}"
    with open(log, "w") as lf:
        subprocess.run(["bash", "-c", cmd], cwd=HERE, stdout=lf, stderr=subprocess.STDOUT, check=True, env=env)


def load(name):
    parts = [np.fromfile(os.path.join(RUNS, f), REC) for f in sorted(os.listdir(RUNS)) if f.startswith(name + "_t") and f.endswith(".bin")]
    return np.concatenate(parts) if parts else np.zeros(0, REC)


def main():
    n_delta = int(sys.argv[1]) if len(sys.argv) > 1 else 2000
    st = json.load(open(os.path.join(W, "story.json")))
    Ed = st["delta_E_keV"]
    # primary energy at the hand-off: kinetic energy after the step that made the delta
    k = st["primary_step_index"]
    prim = [s for s in st["event"]["S"] if s["track"] == 2]
    E_ho = prim[k]["ekin_keV"]
    print(f"delta {Ed:.3f} keV; primary at hand-off {E_ho:.2f} keV")

    m = macro("dna_delta", "opt4", Ed, (0, 0, 0), (3, 3, 3), n_delta, 4242)
    run(m, os.path.join(RUNS, "dna_delta.log"))
    print("delta histories:", len(np.unique(load("dna_delta")["ev"])))

    # energy lost over 20 µm by a fast electron of this energy (short calibration run)
    m = macro("dna_primary_cal", "opt2", E_ho, (0, 0, -20000), (8, 8, 20), 24, 99, threads=4)
    run(m, os.path.join(RUNS, "dna_primary_cal.log"))
    r = load("dna_primary_cal")
    loss = []
    for ev in np.unique(r["ev"]):
        e = r[(r["ev"] == ev) & (r["track"] == 1)]
        k = int(np.argmax(e["z"] >= 0))
        loss.append((e["ekin"][0] - e["ekin"][k]) / 1000.0)  # keV of kinetic energy lost over the first 20 µm
    dE = float(np.mean(loss))
    print(f"mean kinetic-energy loss over 20 µm: {dE:.2f} keV")
    m = macro("dna_primary", "opt2", E_ho + dE, (0, 0, -20000), (8, 8, 20), 400, 1234, threads=4)
    run(m, os.path.join(RUNS, "dna_primary.log"))
    print("primary segments:", len(np.unique(load("dna_primary")["ev"])))
    json.dump({"delta_E_keV": Ed, "primary_E_handoff_keV": E_ho, "primary_E_start_keV": E_ho + dE, "calib_loss_keV": dE},
              open(os.path.join(W, "dna_runs.json"), "w"), indent=1)


if __name__ == "__main__":
    main()
