cmake_minimum_required(VERSION 3.16)
project(nine_orders_sim CXX)
find_package(Geant4 REQUIRED)
include(${Geant4_USE_FILE})
set(CMAKE_CXX_STANDARD 17)
if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Release)
endif()
add_executable(nine_patient patient.cc)
target_link_libraries(nine_patient ${Geant4_LIBRARIES})
add_executable(nine_dna dna.cc)
target_link_libraries(nine_dna ${Geant4_LIBRARIES})
